// <auto-generated />
namespace MY_MVC_APPLICATION.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class EditTraffics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditTraffics));
        
        string IMigrationMetadata.Id
        {
            get { return "202001171406278_EditTraffics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
